(function () {
  "use strict";

  window.WORK_CATEGORIES = {
    "设计": { color: "#F7C31A" },
    "开发": { color: "#2181D5" },
    "人工智能": { color: "#48934B" },
    "产品": { color: "#F3842D" },
    "市场": { color: "#A77F48" },
    "销售": { color: "#C12633" },
    "运营": { color: "#419492" },
    "游戏": { color: "#E96090" },
    "客服": { color: "#409291" },
    "行政": { color: "#CF5A0C" },
    "财务": { color: "#B31727" },
    "教育": { color: "#704A95" },
    "医疗": { color: "#74509A" },
    "写作": { color: "#A77F48" },
    "法务": { color: "#454F7C" }
  };

  window.WORK_DATA_META = {
    updatedAt: "2026-07-18T16:30:00+08:00",
    window: "2026-06-18 至 2026-07-18",
    note: "来自公开招聘帖与职位页；地点只使用帖子中明确出现的城市、国家或远程范围。"
  };

  window.WORK_JOBS = [
    {
      id: "garden3d-head-design",
      title: "Head of Design",
      company: "garden3d",
      category: "设计",
      location: "全球远程",
      lat: 18,
      lng: -32,
      remote: true,
      salary: "$110–175 / 小时",
      posted: "2 小时前",
      attention: 317,
      source: "X",
      sourceUrl: "https://x.com/isaac_idigu/status/2078229658575786235",
      summary: "带领远程设计团队，为全球品牌打造数字产品与品牌体验。",
      tags: ["设计管理", "品牌", "产品设计"],
      evidence: "原帖明确"
    },
    {
      id: "mindgrub-senior-product-designer",
      title: "Senior Product Designer",
      company: "Mindgrub",
      category: "设计",
      location: "美国远程",
      lat: 39.5,
      lng: -98.35,
      remote: true,
      salary: "$60–70 / 小时",
      posted: "6 小时前",
      attention: 1195,
      source: "X",
      sourceUrl: "https://x.com/Timybenson1/status/2078168740210913532",
      summary: "负责用户研究、原型、测试与设计系统，合同制远程岗位。",
      tags: ["用户研究", "设计系统", "原型"],
      evidence: "转发招聘"
    },
    {
      id: "knguru-ux-ui-designer",
      title: "UX/UI Designer",
      company: "Knguru",
      category: "设计",
      location: "欧洲远程",
      lat: 50.1,
      lng: 10.2,
      remote: true,
      salary: "约 €2,000 / 月",
      posted: "3 天前",
      attention: 990,
      source: "X",
      sourceUrl: "https://x.com/DEO_TechJobs/status/2077322137895911782",
      summary: "面向欧洲设计师的自由职业机会，强调 Figma 组件与自动布局能力。",
      tags: ["Figma", "网页", "移动端"],
      evidence: "转发招聘"
    },
    {
      id: "lumapad-ui-ux",
      title: "UI/UX Designer",
      company: "LumaPad",
      category: "设计",
      location: "全球远程",
      lat: -14,
      lng: -145,
      remote: true,
      salary: "$1,500–2,500 / 月",
      posted: "1 天前",
      attention: 6935,
      source: "X",
      sourceUrl: "https://x.com/LumaPad_pro/status/2077987165573648527",
      summary: "为去中心化产品设计界面与完整用户体验。",
      tags: ["Web3", "界面", "体验"],
      evidence: "团队原帖"
    },
    {
      id: "lumapad-frontend",
      title: "Frontend Developer",
      company: "LumaPad",
      category: "开发",
      location: "全球远程",
      lat: -12.5,
      lng: -142,
      remote: true,
      salary: "$2,500–4,000 / 月",
      posted: "1 天前",
      attention: 6935,
      source: "X",
      sourceUrl: "https://x.com/LumaPad_pro/status/2077987165573648527",
      summary: "构建去中心化发行平台的前端体验。",
      tags: ["前端", "Web3", "远程"],
      evidence: "团队原帖"
    },
    {
      id: "lumapad-solidity",
      title: "Solidity Developer",
      company: "LumaPad",
      category: "开发",
      location: "全球远程",
      lat: -10.8,
      lng: -139,
      remote: true,
      salary: "$5,000–8,000 / 月",
      posted: "1 天前",
      attention: 6935,
      source: "X",
      sourceUrl: "https://x.com/LumaPad_pro/status/2077987165573648527",
      summary: "负责智能合约与去中心化产品的链上开发。",
      tags: ["Solidity", "智能合约", "Web3"],
      evidence: "团队原帖"
    },
    {
      id: "twinings-ai-graduate",
      title: "AI Graduate Engineer Trainee",
      company: "Twinings Ovaltine",
      category: "人工智能",
      location: "印度 · 混合办公",
      lat: 22.8,
      lng: 78.9,
      remote: false,
      salary: "未公开",
      posted: "4 天前",
      attention: 3442,
      source: "X",
      sourceUrl: "https://x.com/Rahul1539482/status/2076896497426374952",
      summary: "为毕业生准备的六个月人工智能岗位，涉及 Azure、检索增强和智能体。",
      tags: ["毕业生", "Azure", "RAG"],
      evidence: "转发招聘"
    },
    {
      id: "gnani-ai-intern",
      title: "AI Intern",
      company: "Gnani.ai",
      category: "人工智能",
      location: "印度",
      lat: 12.97,
      lng: 77.59,
      remote: false,
      salary: "未公开",
      posted: "7 天前",
      attention: 6961,
      source: "X",
      sourceUrl: "https://x.com/Rahul1539482/status/2075921772524994569",
      summary: "面向做过语音识别、语音合成、大模型或检索增强项目的实习生。",
      tags: ["语音", "大模型", "实习"],
      evidence: "转发招聘"
    },
    {
      id: "remote-ai-engineers",
      title: "Senior AI Engineer",
      company: "Healthcare AI Team",
      category: "人工智能",
      location: "全球远程",
      lat: 46,
      lng: -158,
      remote: true,
      salary: "美元薪资",
      posted: "1 小时前",
      attention: 2719,
      source: "X",
      sourceUrl: "https://x.com/RemotejobWtessy/status/2078257760894878192",
      summary: "寻找有企业系统、生成式人工智能、数据工程和云端经验的工程师。",
      tags: ["LLM", "MLOps", "医疗"],
      evidence: "招聘汇总"
    },
    {
      id: "techtree-fullstack-ai",
      title: "Full-Stack AI Engineer",
      company: "TechTree Client",
      category: "人工智能",
      location: "伦敦 · 到岗",
      lat: 51.5074,
      lng: -0.1278,
      remote: false,
      salary: "£100k–175k / 年",
      posted: "今天",
      attention: 23,
      source: "X",
      sourceUrl: "https://x.com/afahmy_dev/status/2078381764813144127",
      summary: "使用 Python、React 与云服务构建人工智能产品。",
      tags: ["Python", "React", "AWS"],
      evidence: "转发招聘"
    },
    {
      id: "codecrafters-software-engineer",
      title: "Software Engineer",
      company: "CodeCrafters Client",
      category: "开发",
      location: "全球远程 · 项目制",
      lat: 7,
      lng: -27,
      remote: true,
      salary: "$1,500–3,500 / 项目",
      posted: "7 天前",
      attention: 4341,
      source: "X",
      sourceUrl: "https://x.com/CodeCrafters11/status/2075806762394132672",
      summary: "为成长型公司开发一套定制业务管理系统。",
      tags: ["全栈", "自由职业", "业务系统"],
      evidence: "招聘汇总"
    },
    {
      id: "nigeria-fullstack",
      title: "Full-Stack Developer",
      company: "Jobhorizons Client",
      category: "开发",
      location: "尼日利亚远程",
      lat: 9.08,
      lng: 8.67,
      remote: true,
      salary: "$4,000 / 月",
      posted: "1 天前",
      attention: 362,
      source: "X",
      sourceUrl: "https://x.com/Remote_JobsNG/status/2078027426873966697",
      summary: "使用 Laravel、React 或 Svelte 开发前后端服务，按美东时间协作。",
      tags: ["Laravel", "React", "Svelte"],
      evidence: "转发招聘"
    },
    {
      id: "cet-senior-fullstack",
      title: "Senior Fullstack Developer",
      company: "Jobhorizons Client",
      category: "开发",
      location: "欧洲时区远程",
      lat: 48.4,
      lng: 14.2,
      remote: true,
      salary: "有竞争力",
      posted: "今天",
      attention: 118,
      source: "X",
      sourceUrl: "https://x.com/Remote_JobsNG/status/2078391694890819984",
      summary: "用 Python 与 React 或 Vue 构建可扩展产品，并辅导其他开发者。",
      tags: ["Python", "React", "Vue"],
      evidence: "转发招聘"
    },
    {
      id: "serbia-senior-frontend",
      title: "Senior Frontend Engineer",
      company: "Game Commerce Platform",
      category: "开发",
      location: "塞尔维亚远程",
      lat: 44.79,
      lng: 20.45,
      remote: true,
      salary: "未公开",
      posted: "4 天前",
      attention: 847,
      source: "X",
      sourceUrl: "https://x.com/ZamDeveloper/status/2076969144990277778",
      summary: "为全球游戏商业平台构建高性能 React 应用。",
      tags: ["React", "GraphQL", "游戏"],
      evidence: "转发招聘"
    },
    {
      id: "anthropic-london-senior-engineer",
      title: "Senior Software Engineer",
      company: "Anthropic",
      category: "人工智能",
      location: "伦敦",
      lat: 51.512,
      lng: -0.10,
      remote: false,
      salary: "£225k–325k / 年",
      posted: "3 天前",
      attention: 1362,
      source: "X",
      sourceUrl: "https://x.com/hirehubUKjobs/status/2077273291845169346",
      summary: "伦敦高级软件工程岗位，转发信息称可为符合条件者提供签证支持。",
      tags: ["高级", "签证", "人工智能"],
      evidence: "转发招聘"
    },
    {
      id: "replit-enterprise-product",
      title: "Enterprise Product Manager",
      company: "Replit",
      category: "产品",
      location: "旧金山",
      lat: 37.7749,
      lng: -122.4194,
      remote: false,
      salary: "最高 $300k / 年",
      posted: "4 天前",
      attention: 1689,
      source: "X",
      sourceUrl: "https://x.com/Rahul1539482/status/2076896987367215587",
      summary: "面向企业人工智能开发平台的产品管理岗位。",
      tags: ["企业产品", "人工智能", "平台"],
      evidence: "职位汇总"
    },
    {
      id: "replit-product-data-scientist",
      title: "Data Scientist, Product",
      company: "Replit",
      category: "人工智能",
      location: "旧金山",
      lat: 37.79,
      lng: -122.40,
      remote: false,
      salary: "最高 $250k / 年",
      posted: "4 天前",
      attention: 1689,
      source: "X",
      sourceUrl: "https://x.com/Rahul1539482/status/2076896987367215587",
      summary: "通过数据实验与分析推动人工智能开发产品增长。",
      tags: ["数据科学", "产品", "实验"],
      evidence: "职位汇总"
    },
    {
      id: "goodyear-digital-comms",
      title: "Director of Digital Communications",
      company: "City of Goodyear",
      category: "市场",
      location: "Goodyear · 亚利桑那",
      lat: 33.4353,
      lng: -112.3582,
      remote: false,
      salary: "未公开",
      posted: "今天",
      attention: 128,
      source: "X",
      sourceUrl: "https://x.com/GoodyearAZGov/status/2078283929526706466",
      summary: "负责城市品牌声音、媒体关系、数字策略与社区沟通。",
      tags: ["公共部门", "传播", "数字策略"],
      evidence: "机构原帖"
    },
    {
      id: "remote-video-editor",
      title: "Video Editor",
      company: "Freelance Team",
      category: "设计",
      location: "全球远程",
      lat: -31,
      lng: 164,
      remote: true,
      salary: "$5–7 / 小时",
      posted: "1 天前",
      attention: 7408,
      source: "X",
      sourceUrl: "https://x.com/realAdeyemo/status/2078090111976198387",
      summary: "远程自由职业视频剪辑，接受新人并提供培训。",
      tags: ["视频", "自由职业", "新人"],
      evidence: "个人招聘帖"
    },
    {
      id: "remote-email-marketing",
      title: "Email Marketing Specialist",
      company: "Freelance Team",
      category: "市场",
      location: "全球远程",
      lat: -28,
      lng: 158,
      remote: true,
      salary: "$5–7 / 小时",
      posted: "1 天前",
      attention: 7408,
      source: "X",
      sourceUrl: "https://x.com/realAdeyemo/status/2078090111976198387",
      summary: "负责远程团队的邮件营销与基础增长工作。",
      tags: ["邮件", "增长", "新人"],
      evidence: "个人招聘帖"
    },
    {
      id: "remote-social-media",
      title: "Social Media Manager",
      company: "Freelance Team",
      category: "市场",
      location: "全球远程",
      lat: -25,
      lng: 153,
      remote: true,
      salary: "$5–7 / 小时",
      posted: "1 天前",
      attention: 7408,
      source: "X",
      sourceUrl: "https://x.com/realAdeyemo/status/2078090111976198387",
      summary: "管理社交内容与日常发布，接受新人。",
      tags: ["社交媒体", "内容", "新人"],
      evidence: "个人招聘帖"
    },
    {
      id: "remote-senior-sdr",
      title: "Senior Sales Development Representative",
      company: "Wellness Clinic Marketing",
      category: "销售",
      location: "全球远程",
      lat: 33,
      lng: -165,
      remote: true,
      salary: "$10k–25k",
      posted: "2 小时前",
      attention: 199,
      source: "X",
      sourceUrl: "https://x.com/isaac_idigu/status/2078236643350180044",
      summary: "负责获客、线索开发与成交机会推进。原帖未说明薪资周期，申请前需核实。",
      tags: ["获客", "销售", "远程"],
      evidence: "转发招聘"
    },
    {
      id: "remote-sdr-na",
      title: "Sales Development Representative",
      company: "Jobhorizons Client",
      category: "销售",
      location: "欧美时区远程",
      lat: 43,
      lng: -62,
      remote: true,
      salary: "底薪 + 佣金",
      posted: "1 天前",
      attention: 299,
      source: "X",
      sourceUrl: "https://x.com/Remote_JobsNG/status/2078026969061503282",
      summary: "面向英国、欧洲与北美客户开展外呼、研究与销售线索管理。",
      tags: ["销售开发", "CRM", "欧美"],
      evidence: "转发招聘"
    },
    {
      id: "fullscale-engineering-ph",
      title: "Software Engineering Roles",
      company: "Full Scale",
      category: "开发",
      location: "菲律宾远程",
      lat: 14.5995,
      lng: 120.9842,
      remote: true,
      salary: "未公开",
      posted: "本周",
      attention: 33,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/PinoyProgrammer/comments/1uk4i3w/who_is_hiring_july_2026/",
      summary: "面向菲律宾候选人的长期远程工程岗位，包含设备、保险与居家补贴。",
      tags: ["菲律宾", "远程", "全职"],
      evidence: "社区招聘串"
    },
    {
      id: "ofi-junior-fullstack",
      title: "Junior Full Stack Developer",
      company: "O-KUN Frontier Innovations",
      category: "开发",
      location: "Pasig · 混合办公",
      lat: 14.5764,
      lng: 121.0851,
      remote: false,
      salary: "₱20k–26k / 月",
      posted: "本周",
      attention: 33,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/PinoyProgrammer/comments/1uk4i3w/who_is_hiring_july_2026/",
      summary: "为本地与国际客户开发真实产品，每周到岗一天，欢迎应届生。",
      tags: ["Next.js", "AWS", "应届"],
      evidence: "公司回复"
    },
    {
      id: "ofi-web-intern",
      title: "Web Development Intern",
      company: "O-KUN Frontier Innovations",
      category: "开发",
      location: "Pasig · 混合办公",
      lat: 14.59,
      lng: 121.10,
      remote: false,
      salary: "₱7k–12k / 月",
      posted: "本周",
      attention: 33,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/PinoyProgrammer/comments/1uk4i3w/who_is_hiring_july_2026/",
      summary: "三至四个月的带薪开发实习，使用 Next.js、React 与 CSS。",
      tags: ["实习", "React", "Web"],
      evidence: "公司回复"
    },
    {
      id: "optibpo-graphic-designer",
      title: "Graphic Designer",
      company: "OptiBPO",
      category: "设计",
      location: "美国远程",
      lat: 38.2,
      lng: -96.1,
      remote: true,
      salary: "$25–40 / 小时",
      posted: "本周",
      attention: 95,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/hiring/comments/1uyv4tc/hiring_graphic_designer_fulltime_25_40hourly/",
      summary: "制作品牌、社交媒体、数字与印刷营销素材。",
      tags: ["平面", "品牌", "营销"],
      evidence: "社区招聘帖"
    },
    {
      id: "cmg-webflow-designer",
      title: "Webflow Designer / Developer",
      company: "CMG Visuals",
      category: "设计",
      location: "Dallas · 远程合作",
      lat: 32.7767,
      lng: -96.797,
      remote: true,
      salary: "项目制",
      posted: "5 天前",
      attention: 8,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/webflow/comments/1uvcg49/weekly_hiring_thread_july_13_2026/",
      summary: "重做 Webflow 导航和案例模板，要求能直接在 Webflow 中设计与搭建。",
      tags: ["Webflow", "CMS", "网页"],
      evidence: "公司回复"
    },
    {
      id: "india-graphic-intern",
      title: "Graphic Design Intern",
      company: "Mood Tracker Team",
      category: "设计",
      location: "印度远程",
      lat: 20.59,
      lng: 78.96,
      remote: true,
      salary: "₹12k–18k / 月",
      posted: "6 天前",
      attention: 22,
      source: "Reddit",
      sourceUrl: "https://www.reddit.com/r/InternshipsIndia/comments/1use7ma/hiring_graphic_design_intern_remote/",
      summary: "为情绪健康产品设计情绪卡片、社交素材与视觉风格。",
      tags: ["实习", "插画", "情绪健康"],
      evidence: "社区招聘帖"
    },
    {
      id: "east-midlands-graphic",
      title: "Graphic Designer",
      company: "Martin Veasey Client",
      category: "设计",
      location: "East Midlands · 到岗",
      lat: 52.83,
      lng: -1.33,
      remote: false,
      salary: "有竞争力 + 奖金",
      posted: "2 天前",
      attention: 66,
      source: "X",
      sourceUrl: "https://x.com/MVTalent/status/2077845896503419005",
      summary: "负责品牌、网页、社交与印刷设计，需要熟悉 Adobe 工具。",
      tags: ["Adobe", "品牌", "印刷"],
      evidence: "招聘机构原帖"
    },
    {
      id: "joblume-fullstack-us",
      title: "Full-Stack Developer",
      company: "AI Infrastructure Team",
      category: "开发",
      location: "美国远程",
      lat: 40.1,
      lng: -101.8,
      remote: true,
      salary: "$130k–180k / 年",
      posted: "今天",
      attention: 120,
      source: "招聘网站",
      sourceUrl: "https://joblume.totalh.net/job/full-stack-developer-react-node-js-remote-us-timezone-overlap",
      summary: "构建服务前沿人工智能实验室的全栈系统，需要与美西时区重叠。",
      tags: ["TypeScript", "Node.js", "PostgreSQL"],
      evidence: "职位页"
    },
    {
      id: "polcode-python-ai",
      title: "Python Backend Engineer",
      company: "Polcode",
      category: "人工智能",
      location: "波兰远程 / 华沙",
      lat: 52.2297,
      lng: 21.0122,
      remote: true,
      salary: "未公开",
      posted: "今天",
      attention: 82,
      source: "招聘网站",
      sourceUrl: "https://hirro.kesug.com/job/python-backend-engineer-llm-data-pipelines-us-ai-product",
      summary: "为美国人工智能产品构建文档抽取、数据管道与大模型工作流。",
      tags: ["Python", "数据管道", "LLM"],
      evidence: "职位页"
    },
    {
      id: "capitalone-lead-ai",
      title: "Lead AI Engineer",
      company: "Capital One",
      category: "人工智能",
      location: "纽约 · 混合办公",
      lat: 40.7128,
      lng: -74.006,
      remote: false,
      salary: "$197k–246k / 年",
      posted: "20 小时前",
      attention: 260,
      source: "领英 / 职位页",
      sourceUrl: "https://www.linkedin.com/jobs/artificial-intelligence-engineer-jobs",
      summary: "开发与部署人工智能组件，优化大模型系统并与产品团队协作。",
      tags: ["LLM", "PyTorch", "云平台"],
      evidence: "职位聚合页"
    },
    {
      id: "mastercard-forward-ai",
      title: "Forward-Deployed AI Engineer",
      company: "Mastercard",
      category: "人工智能",
      location: "纽约 · 混合办公",
      lat: 40.73,
      lng: -73.98,
      remote: false,
      salary: "$140k–266k / 年",
      posted: "7 天前",
      attention: 190,
      source: "领英 / 职位页",
      sourceUrl: "https://www.linkedin.com/jobs/artificial-intelligence-engineer-jobs",
      summary: "深入业务团队，设计并部署人工智能助手与多智能体方案。",
      tags: ["智能体", "RAG", "企业转型"],
      evidence: "职位聚合页"
    },
    {
      id: "roberthalf-data-engineer",
      title: "Data Engineer",
      company: "Robert Half Client",
      category: "开发",
      location: "Kalamazoo · 远程",
      lat: 42.2917,
      lng: -85.5872,
      remote: true,
      salary: "$150k–225k / 年",
      posted: "5 天前",
      attention: 75,
      source: "招聘网站",
      sourceUrl: "https://www.roberthalf.com/us/en/job/kalamazoo-mi/data-engineer/02220-0013436476-usen",
      summary: "设计多租户数据平台、批处理与流式管道，支持分析和人工智能产品。",
      tags: ["数据平台", "流处理", "架构"],
      evidence: "职位页"
    },
    {
      id: "roberthalf-creative-director",
      title: "Creative Director",
      company: "Robert Half Client",
      category: "设计",
      location: "Lakeland · 远程",
      lat: 28.0395,
      lng: -81.9498,
      remote: true,
      salary: "合同制",
      posted: "3 天前",
      attention: 61,
      source: "招聘网站",
      sourceUrl: "https://www.roberthalf.com/us/en/jobs",
      summary: "领导品牌视觉、视频、动态设计与跨渠道创意团队。",
      tags: ["创意管理", "视频", "品牌"],
      evidence: "职位页"
    },
    {
      id: "roberthalf-solution-architect",
      title: "Solution Architect",
      company: "Robert Half Client",
      category: "开发",
      location: "Ann Arbor · 远程",
      lat: 42.2808,
      lng: -83.743,
      remote: true,
      salary: "$140k–150k / 年",
      posted: "3 天前",
      attention: 54,
      source: "招聘网站",
      sourceUrl: "https://www.roberthalf.com/us/en/jobs",
      summary: "设计并交付客户实施方案，连接 Salesforce、工作流和自动化。",
      tags: ["Salesforce", "架构", "客户成功"],
      evidence: "职位页"
    },
    {
      id: "wifi-tribe-community-leader",
      title: "Community Leader",
      company: "WiFi Tribe",
      category: "运营",
      location: "全球旅行 · 远程",
      lat: -42,
      lng: -7,
      remote: true,
      salary: "$1.5k–5k / 月",
      posted: "5 天前",
      attention: 240,
      source: "招聘网站",
      sourceUrl: "https://dynamitejobs.com/",
      summary: "带领远程工作者旅行社群，需要在多个国家之间移动。",
      tags: ["社群", "旅行", "远程"],
      evidence: "职位页"
    },
    {
      id: "owlcat-game-designer",
      title: "Game Designer",
      company: "Owlcat Games",
      category: "游戏",
      location: "欧洲 / 远程",
      lat: 35.1264,
      lng: 33.4299,
      remote: true,
      salary: "未公开",
      posted: "1 天前",
      attention: 3555,
      source: "X",
      sourceUrl: "https://x.com/80Level/status/2078125069981855823",
      summary: "参与大型角色扮演游戏的系统、关卡和玩法设计。",
      tags: ["RPG", "关卡", "游戏系统"],
      evidence: "行业媒体转发"
    }
  ];
})();
